version: 2.1
orbs:
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/python:2.7-node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
  test:
    jobs:
      - test